import { Block, Household, Bill, FundUsage, ReminderLog, HouseStatus } from "@/types/database";

export const HOUSE_STATUS_RATES = {
  tetap: 10000,
  kontrakan: 5000,
} as const;

export const HOUSE_STATUS_CONFIG = {
  tetap: {
    label: "Rumah Tetap",
    fullLabel: "Rumah Tetap / Milik Sendiri",
    monthlyDue: 10000,
    badgeBg: "bg-blue-50 text-blue-700 border-blue-200",
  },
  kontrakan: {
    label: "Kontrakan",
    fullLabel: "Rumah Kontrakan / Sewa",
    monthlyDue: 5000,
    badgeBg: "bg-amber-50 text-amber-700 border-amber-200",
  },
} as const;

export const mockBlocks: Block[] = [
  { id: "blk-a", name: "Blok A", monthly_due_amount: 10000, total_houses: 32 },
  { id: "blk-b", name: "Blok B", monthly_due_amount: 10000, total_houses: 36 },
  { id: "blk-c", name: "Blok C", monthly_due_amount: 5000, total_houses: 30 },
  { id: "blk-d", name: "Blok D", monthly_due_amount: 5000, total_houses: 30 },
];

export const mockHouseholds: Household[] = [
  {
    id: "hh-01",
    house_status: "tetap",
    house_number: "A-07",
    head_of_family_name: "Joko Pranoto",
    contact: "0812-3456-7890",
    access_code: "RH-A7-X8K2",
    is_active: true,
  },
  {
    id: "hh-02",
    house_status: "kontrakan",
    house_number: "C-15",
    head_of_family_name: "Lina Marlina",
    contact: "0813-2222-1144",
    access_code: "RH-C15-Q9L4",
    is_active: true,
  },
  {
    id: "hh-03",
    house_status: "kontrakan",
    house_number: "B-03",
    head_of_family_name: "Dedi Setiawan",
    contact: "0821-6655-8833",
    access_code: "RH-B3-M2P7",
    is_active: true,
  },
  {
    id: "hh-04",
    house_status: "tetap",
    house_number: "B-12",
    head_of_family_name: "Rudi Hartono",
    contact: "0819-7788-9900",
    access_code: "RH-B12-K7N3",
    is_active: true,
  },
  {
    id: "hh-05",
    house_status: "tetap",
    house_number: "C-08",
    head_of_family_name: "Siti Wahyuni",
    contact: "0857-1122-3344",
    access_code: "RH-C8-W4E9",
    is_active: true,
  },
  {
    id: "hh-06",
    house_status: "kontrakan",
    house_number: "D-04",
    head_of_family_name: "Andi Firmansyah",
    contact: "0878-5544-3322",
    access_code: "RH-D4-F5Y1",
    is_active: true,
  },
  {
    id: "hh-07",
    house_status: "tetap",
    house_number: "A-19",
    head_of_family_name: "Dewi Lestari",
    contact: "0811-9988-7766",
    access_code: "RH-A19-T2R6",
    is_active: true,
  },
  {
    id: "hh-08",
    house_status: "tetap",
    house_number: "A-02",
    head_of_family_name: "Agus Prasetyo",
    contact: "0812-9876-5432",
    access_code: "RH-A2-H3L9",
    is_active: true,
  },
];

export const mockBills: Bill[] = [
  {
    id: "bill-01",
    household_id: "hh-01",
    household_name: "Joko Pranoto",
    house_number: "A-07",
    house_status: "tetap",
    block_name: "Rumah Tetap",
    period: "September 2026",
    amount: 10000,
    paid_amount: 10000,
    status: "paid",
    due_date: "10 Sep 2026",
    method: "transfer",
    paid_at: "8 Sep 2026, 09:42",
    notes: "Bukti transfer BCA terlampir",
  },
  {
    id: "bill-02",
    household_id: "hh-02",
    household_name: "Lina Marlina",
    house_number: "C-15",
    house_status: "kontrakan",
    block_name: "Kontrakan",
    period: "September 2026",
    amount: 5000,
    paid_amount: 5000,
    status: "paid",
    due_date: "10 Sep 2026",
    method: "transfer",
    paid_at: "8 Sep 2026, 08:18",
    notes: "Lunas tepat waktu",
  },
  {
    id: "bill-03",
    household_id: "hh-03",
    household_name: "Dedi Setiawan",
    house_number: "B-03",
    house_status: "kontrakan",
    block_name: "Kontrakan",
    period: "September 2026",
    amount: 5000,
    paid_amount: 3000,
    status: "partial",
    due_date: "10 Sep 2026",
    method: "cash",
    paid_at: "12 Sep 2026, 17:30",
    notes: "Sisa Rp 2.000 dibayar akhir bulan",
  },
  {
    id: "bill-04",
    household_id: "hh-04",
    household_name: "Rudi Hartono",
    house_number: "B-12",
    house_status: "tetap",
    block_name: "Rumah Tetap",
    period: "September 2026",
    amount: 10000,
    paid_amount: 0,
    status: "unpaid",
    due_date: "10 Sep 2026",
    notes: "Menunggak",
  },
  {
    id: "bill-05",
    household_id: "hh-05",
    household_name: "Siti Wahyuni",
    house_number: "C-08",
    house_status: "tetap",
    block_name: "Rumah Tetap",
    period: "September 2026",
    amount: 10000,
    paid_amount: 0,
    status: "unpaid",
    due_date: "10 Sep 2026",
    notes: "Menunggu kiriman keluarga",
  },
  {
    id: "bill-06",
    household_id: "hh-06",
    household_name: "Andi Firmansyah",
    house_number: "D-04",
    house_status: "kontrakan",
    block_name: "Kontrakan",
    period: "September 2026",
    amount: 5000,
    paid_amount: 0,
    status: "unpaid",
    due_date: "10 Sep 2026",
  },
  {
    id: "bill-07",
    household_id: "hh-07",
    household_name: "Dewi Lestari",
    house_number: "A-19",
    house_status: "tetap",
    block_name: "Rumah Tetap",
    period: "September 2026",
    amount: 10000,
    paid_amount: 0,
    status: "unpaid",
    due_date: "10 Sep 2026",
  },
];

export const mockFundUsages: FundUsage[] = [
  {
    id: "fu-01",
    period: "September 2026",
    category: "Keamanan Lingkungan & Satpam",
    amount: 2500000,
    description: "Gaji 2 petugas jaga malam dan operasional pos satpam",
    icon_type: "shield",
  },
  {
    id: "fu-02",
    period: "September 2026",
    category: "Kebersihan & Pengangkutan Sampah",
    amount: 1400000,
    description: "Retribusi armada angkut sampah RT 3x seminggu",
    icon_type: "trash",
  },
  {
    id: "fu-03",
    period: "September 2026",
    category: "Penerangan Jalan & Fasilitas Umum",
    amount: 1250000,
    description: "Token listrik pos ronda, PJU gang, dan servis pompa air taman",
    icon_type: "zap",
  },
  {
    id: "fu-04",
    period: "September 2026",
    category: "Kegiatan Sosial & Warga",
    amount: 850000,
    description: "Santunan duka warga & konsumsi kerja bakti RT",
    icon_type: "users",
  },
];

export const mockReminders: ReminderLog[] = [
  {
    id: "rem-01",
    bill_id: "bill-04",
    household_name: "Rudi Hartono",
    house_number: "B-12",
    overdue_months: 2,
    sent_at: "20 Sep 2026, 10:00",
    channel: "WhatsApp",
    status: "Terkirim",
  },
  {
    id: "rem-02",
    bill_id: "bill-05",
    household_name: "Siti Wahyuni",
    house_number: "C-08",
    overdue_months: 1,
    sent_at: "20 Sep 2026, 10:01",
    channel: "Portal Warga",
    status: "Terkirim",
  },
  {
    id: "rem-03",
    bill_id: "bill-06",
    household_name: "Andi Firmansyah",
    house_number: "D-04",
    overdue_months: 1,
    sent_at: "20 Sep 2026, 10:02",
    channel: "Portal Warga",
    status: "Terkirim",
  },
];

export function formatRupiah(amount: number): string {
  return "Rp " + amount.toLocaleString("id-ID");
}
